import React from 'react';
import { Check, ArrowRight, TrendingUp, Box, Layers } from 'lucide-react';
import { GlassCard } from '../components/ui/GlassCard';
import { SectionLabel } from '../components/ui/SectionLabel';

export const Aetheo: React.FC = () => {
  return (
    <div className="animate-in fade-in duration-700">
      <header className="text-center mb-24 flex flex-col items-center mt-8">
        <p className="text-xs font-bold tracking-[0.2em] uppercase text-teal-400 mb-6 flex items-center gap-2">
          <Check size={14} /> Proof Layer
        </p>
        <h1 className="text-5xl md:text-7xl font-bold text-white tracking-tight mb-8 leading-[1.1] max-w-4xl">
          AETHEO: <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-green-400">The Live System.</span>
        </h1>
        <p className="text-lg md:text-xl text-gray-400 max-w-2xl leading-relaxed">
          This actually works in real life. See how Puniverse powers a premium UK wellness brand.
        </p>
      </header>

      <section className="mb-32">
        <SectionLabel>Brand Overview</SectionLabel>
        <div className="rounded-2xl border border-teal-500/30 bg-teal-500/5 p-8 md:p-12 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-teal-500/10 blur-[80px] rounded-full"></div>
          <div className="relative z-10 max-w-3xl mx-auto text-center">
            <h3 className="text-3xl font-bold text-white mb-6">From Dropshipping to Premium</h3>
            <p className="text-lg text-teal-200 mb-8 leading-relaxed">
              AETHEO started as a standard dropshipping operation. By implementing the Puniverse OS, it has transitioned into a premium UK-based wellness brand with automated supply chains, content generation, and product development.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <span className="px-4 py-2 rounded-full border border-teal-500/30 bg-teal-500/10 text-sm text-teal-300">
                Dropshipping &rarr; Premium Brand
              </span>
              <span className="px-4 py-2 rounded-full border border-teal-500/30 bg-teal-500/10 text-sm text-teal-300">
                Manual &rarr; Autonomous
              </span>
            </div>
          </div>
        </div>
      </section>

      <section className="mb-32">
        <SectionLabel>Systems Used</SectionLabel>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <GlassCard>
            <div className="w-10 h-10 rounded-lg bg-white/5 flex items-center justify-center border border-white/10 mb-6">
              <TrendingUp className="text-teal-400" size={20} />
            </div>
            <h3 className="text-xl font-medium text-white mb-4">SEO Automation</h3>
            <p className="text-sm text-gray-400 leading-relaxed">
              Programmatic SEO pages and blog content generated by AI agents to capture long-tail wellness search intent.
            </p>
          </GlassCard>
          <GlassCard highlight>
            <div className="w-10 h-10 rounded-lg bg-teal-500/10 flex items-center justify-center border border-teal-500/20 mb-6">
              <Layers className="text-teal-400" size={20} />
            </div>
            <h3 className="text-xl font-medium text-white mb-4">Content Pipelines</h3>
            <p className="text-sm text-gray-300 leading-relaxed">
              Automated video generation for YouTube and TikTok, plus AI-assisted copywriting for product pages and ads.
            </p>
          </GlassCard>
          <GlassCard>
            <div className="w-10 h-10 rounded-lg bg-white/5 flex items-center justify-center border border-white/10 mb-6">
              <Box className="text-teal-400" size={20} />
            </div>
            <h3 className="text-xl font-medium text-white mb-4">Product Development</h3>
            <p className="text-sm text-gray-400 leading-relaxed">
              Using AI to analyze market gaps, formulate product ideas, and manage supplier communications.
            </p>
          </GlassCard>
        </div>
      </section>
    </div>
  );
};
